services:
  oidc-playground:
    image: ghcr.io/thesaineyereg/oidc-playground:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oidc-playground
    ports:
      - "4200:4200"
    restart: unless-stopped